name: hypercontroller
channels:
  - conda-forge
dependencies:
  - matplotlib-inline=0.1.7
  - pip=25.0.1
  - python=3.11.11
  - pip:
      - accelerate
      - bitsandbytes
      - box2d
      - datasets
      - gpy==1.13.2
      - gym==0.26.2
      - gym-notices==0.0.8
      - huggingface
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jupyterlab-server==2.27.3
      - matplotlib==3.10.0
      - mujoco==3.2.7
      - numpy==1.26.4
      - pandas==2.2.3
      - ray==2.43.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - sentencepiece
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensordict==0.6.2
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchdata==0.11.0
      - torchrl==0.6.0
      - torchtune==0.5.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers
      - peft
      - pygame==2.6.1
      - pytest==8.3.5